set_property SRC_FILE_INFO {cfile:c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodTMP3_0_0/design_1_PmodTMP3_0_0_board.xdc rfile:../../../Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodTMP3_0_0/design_1_PmodTMP3_0_0_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:inst prop_thru_buffer:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC1} [get_ports Pmod_out_pin1_t]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC2} [get_ports Pmod_out_pin2_t]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC7} [get_ports Pmod_out_pin7_t]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC8} [get_ports Pmod_out_pin8_t]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC9} [get_ports Pmod_out_pin9_t]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JC10} [get_ports Pmod_out_pin10_t]
