# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/design_1_PmodRTCC_0_0.xci
# IP: The module: 'design_1_PmodRTCC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_axi_iic_0_0 || ORIG_REF_NAME==PmodRTCC_axi_iic_0_0}]

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/PmodRTCC_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodRTCC_pmod_bridge_0_0}]

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_xlconstant_0_0/PmodRTCC_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_xlconstant_0_0 || ORIG_REF_NAME==PmodRTCC_xlconstant_0_0}]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/design_1_PmodRTCC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodRTCC_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodRTCC_axi_iic_0_0 || ORIG_REF_NAME==PmodRTCC_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0_ooc.xdc

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/PmodRTCC_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodRTCC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodRTCC_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodRTCC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/design_1_PmodRTCC_0_0.xci
# IP: The module: 'design_1_PmodRTCC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_axi_iic_0_0 || ORIG_REF_NAME==PmodRTCC_axi_iic_0_0}]

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/PmodRTCC_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodRTCC_pmod_bridge_0_0}]

# IP: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_xlconstant_0_0/PmodRTCC_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodRTCC_xlconstant_0_0 || ORIG_REF_NAME==PmodRTCC_xlconstant_0_0}]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/design_1_PmodRTCC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodRTCC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodRTCC_axi_iic_0_0 || ORIG_REF_NAME==PmodRTCC_axi_iic_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_axi_iic_0_0/PmodRTCC_axi_iic_0_0_ooc.xdc

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/PmodRTCC_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodRTCC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodRTCC_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/Xilinx/Vivado/Final_Project_RTCC_TMP3/Final_Project_RTCC_TMP3.srcs/sources_1/bd/design_1/ip/design_1_PmodRTCC_0_0/src/PmodRTCC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodRTCC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
